### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by michael-hatz** [martin-ueding/geo-activity-playground#257]
Hi Martin,

I'm on Ubuntu 24.04 and updated GAP with pipx upgrade --pip-args "--upgrade-strategy eager" geo-activity-playground as in the documentation. When trying to start the program from the existing folder with "geo-activity-playground serve", I'm getting this error: 

```
michael@thinkcentre:~/geoactivity$ geo-activity-playground serve
2025-04-16 07:14:29 alembic.runtime.migration INFO Context impl SQLiteImpl.
2025-04-16 07:14:29 alembic.runtime.migration INFO Will assume non-transactional DDL.
Import from Strava export: 0it [00:00, ?it/s]
2025-04-16 07:14:32 root ERROR Please make sure your STRAVA_CLIENT_ID is set in your environment.
2025-04-16 07:14:32 root WARNING STRAVA_CLIENT_ID and STRAVA_CLIENT_SECRET not found in your  environment. Please refresh your access_token manually. Or add STRAVA_CLIENT_ID and STRAVA_CLIENT_SECRET to your environment.
Downloading Strava activities: 0it [00:00, ?it/s]
Importing new activities into database:   0%|                                                                                    | 0/6095 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/michael/.local/bin/geo-activity-playground", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/michael/.local/share/pipx/venvs/geo-activity-playground/lib/python3.12/site-packages/geo_activity_playground/__main__.py", line 84, in main
    options.func(options)
  File "/home/michael/.local/share/pipx/venvs/geo-activity-playground/lib/python3.12/site-packages/geo_activity_playground/__main__.py", line 50, in <lambda>
    func=lambda options: web_ui_main(
                         ^^^^^^^^^^^^
  File "/home/michael/.local/share/pipx/venvs/geo-activity-playground/lib/python3.12/site-packages/geo_activity_playground/webui/app.py", line 90, in web_ui_main
    scan_for_activities(repository, tile_visit_accessor, config_accessor())
  File "/home/michael/.local/share/pipx/venvs/geo-activity-playground/lib/python3.12/site-packages/geo_activity_playground/webui/blueprints/upload_blueprint.py", line 114, in scan_for_activities
    populate_database_from_extracted(config)
  File "/home/michael/.local/share/pipx/venvs/geo-activity-playground/lib/python3.12/site-packages/geo_activity_playground/core/enrichment.py", line 68, in populate_database_from_extracted
    kind = get_or_make_kind(kind_name, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/.local/share/pipx/venvs/geo-activity-playground/lib/python3.12/site-packages/geo_activity_playground/core/datamodel.py", line 237, in get_or_make_kind
    consider_for_achievements=config.kinds_without_achievements.get(name, True),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

```

**Comment by jottojott** [comment]
Same here.
After running the latest update:
`jochen@T570:~$` pipx upgrade geo-activity-playground
upgraded package geo-activity-playground from 0.38.2 to 0.39.0 (location: /home/jochen/.local/pipx/venvs/geo-activity-playground)
``
I got the same error:
``jochen@T570:~$ geo-activity-playground --basedir ~/Dokumente/Apps/Playground serve
2025-04-16 21:46:07 alembic.runtime.migration INFO Context impl SQLiteImpl.
2025-04-16 21:46:07 alembic.runtime.migration INFO Will assume non-transactional DDL.
2025-04-16 21:46:07 alembic.runtime.migration INFO Running upgrade  -> 63d3b7f6f93c
2025-04-16 21:46:08 alembic.runtime.migration INFO Running upgrade 63d3b7f6f93c -> b03491c593f6
2025-04-16 21:46:08 alembic.runtime.migration INFO Running upgrade b03491c593f6 -> ab83b9d23127
2025-04-16 21:46:08 alembic.runtime.migration INFO Running upgrade ab83b9d23127 -> 451e7836b53d
2025-04-16 21:46:08 alembic.runtime.migration INFO Running upgrade 451e7836b53d -> e02e27876deb
2025-04-16 21:46:09 geo_activity_playground.core.config WARNING You have an old 'config.toml' which is now superseded by the 'config.json'. You can check the contents of the new 'config.json' and then delete the old 'config.toml'.
2025-04-16 21:46:09 geo_activity_playground.importers.strava_api INFO Renew Strava access token …
2025-04-16 21:46:09 root ERROR Please make sure your STRAVA_CLIENT_ID is set in your environment.
2025-04-16 21:46:09 root WARNING STRAVA_CLIENT_ID and STRAVA_CLIENT_SECRET not found in your  environment. Please refresh your access_token manually. Or add STRAVA_CLIENT_ID and STRAVA_CLIENT_SECRET to your environment.
2025-04-16 21:46:09 stravalib.util.limiter.SleepingRateLimitRule WARNING No rates present in response headers
2025-04-16 21:46:09 root ERROR Please make sure your STRAVA_CLIENT_ID is set in your environment.
2025-04-16 21:46:09 root WARNING STRAVA_CLIENT_ID and STRAVA_CLIENT_SECRET not found in your  environment. Please refresh your access_token manually. Or add STRAVA_CLIENT_ID and STRAVA_CLIENT_SECRET to your environment.
Downloading Strava activities: 0it [00:00, ?it/s]2025-04-16 21:46:10 geo_activity_playground.importers.strava_api ERROR The activity 14188216816 with name “Faustball” cannot be found.Perhaps it is a manual activity without a time series. Ignoring. e=ObjectNotFound('Not Found: Resource Not Found: []')
Downloading Strava activities: 1it [00:00,  1.33it/s]
Importing new activities into database:   0%|                                                                | 0/93 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/jochen/.local/bin/geo-activity-playground", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jochen/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/__main__.py", line 84, in main
    options.func(options)
  File "/home/jochen/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/__main__.py", line 50, in <lambda>
    func=lambda options: web_ui_main(
                         ^^^^^^^^^^^^
  File "/home/jochen/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/webui/app.py", line 90, in web_ui_main
    scan_for_activities(repository, tile_visit_accessor, config_accessor())
  File "/home/jochen/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/webui/blueprints/upload_blueprint.py", line 114, in scan_for_activities
    populate_database_from_extracted(config)
  File "/home/jochen/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/core/enrichment.py", line 68, in populate_database_from_extracted
    kind = get_or_make_kind(kind_name, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jochen/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/core/datamodel.py", line 237, in get_or_make_kind
    consider_for_achievements=config.kinds_without_achievements.get(name, True),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
``

**Comment by biker793** [comment]
After upgrading to 0.39.0 the same for me:
`(geo-play) chris@fedora:~/Documents/Playground$ geo-activity-playground serve
2025-04-17 14:32:50 alembic.runtime.migration INFO Context impl SQLiteImpl.
2025-04-17 14:32:50 alembic.runtime.migration INFO Will assume non-transactional DDL.
Import from Strava export: 0it [00:00, ?it/s]
Downloading Strava activities: 0it [00:00, ?it/s]
Importing new activities into database:   0%|                                                                                                                                                                       | 0/1673 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/chris/miniforge3/envs/geo-play/bin/geo-activity-playground", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/chris/miniforge3/envs/geo-play/lib/python3.12/site-packages/geo_activity_playground/__main__.py", line 84, in main
    options.func(options)
  File "/home/chris/miniforge3/envs/geo-play/lib/python3.12/site-packages/geo_activity_playground/__main__.py", line 50, in <lambda>
    func=lambda options: web_ui_main(
                         ^^^^^^^^^^^^
  File "/home/chris/miniforge3/envs/geo-play/lib/python3.12/site-packages/geo_activity_playground/webui/app.py", line 90, in web_ui_main
    scan_for_activities(repository, tile_visit_accessor, config_accessor())
  File "/home/chris/miniforge3/envs/geo-play/lib/python3.12/site-packages/geo_activity_playground/webui/blueprints/upload_blueprint.py", line 114, in scan_for_activities
    populate_database_from_extracted(config)
  File "/home/chris/miniforge3/envs/geo-play/lib/python3.12/site-packages/geo_activity_playground/core/enrichment.py", line 68, in populate_database_from_extracted
    kind = get_or_make_kind(kind_name, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/miniforge3/envs/geo-play/lib/python3.12/site-packages/geo_activity_playground/core/datamodel.py", line 237, in get_or_make_kind
    consider_for_achievements=config.kinds_without_achievements.get(name, True),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'`

**Comment by martin-ueding** [comment]
Thanks for the report. That was a stupid mistake and a lack of testing. I've fixed that.

I've published version 0.39.1 with the fix.

**Comment by jottojott** [comment]
Ah, yes that one may be closed, but still:
Clicking on *any* activities on the main screen leads to
"Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
I open another issue-
