### ISSUE TITLE
TypeError: Cannot compare tz-naive and tz-aware timestamps

### ISSUE THREAD

**Issue by beautiful-orca** [martin-ueding/geo-activity-playground#309]
I had geo-activity-playground version 1.2.0 running with my existing activities.
I updated to version 1.3.0 and started the docker container.
In the logs i encountered the following error:

```
geo-activity  | 2025-07-08 19:23:23 geo_activity_playground.importers.directory INFO Importing Activities/Ride/Trekkingrad/2025-05-05_20-26_Mon.gpx …
geo-activity  | Exception in thread Thread-2 (importer_thread):
geo-activity  | Traceback (most recent call last):
geo-activity  |   File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
geo-activity  |     self.run()
geo-activity  |   File "/usr/local/lib/python3.12/threading.py", line 1012, in run
geo-activity  |     self._target(*self._args, **self._kwargs)
geo-activity  |   File "/app/geo_activity_playground/webui/app.py", line 87, in importer_thread
geo-activity  |     scan_for_activities(repository, tile_visit_accessor, config)
geo-activity  |   File "/app/geo_activity_playground/webui/blueprints/upload_blueprint.py", line 121, in scan_for_activities
geo-activity  |     import_from_directory(repository, tile_visit_accessor, config)
geo-activity  |   File "/app/geo_activity_playground/importers/directory.py", line 47, in import_from_directory
geo-activity  |     import_from_file(activity_path, repository, tile_visit_accessor, config)
geo-activity  |   File "/app/geo_activity_playground/importers/directory.py", line 89, in import_from_file
geo-activity  |     compute_tile_visits_new(repository, tile_visit_accessor)
geo-activity  |   File "/app/geo_activity_playground/explorer/tile_visits.py", line 148, in compute_tile_visits_new
geo-activity  |     _process_activity(repository, tile_visit_accessor.tile_state, activity_id)
geo-activity  |   File "/app/geo_activity_playground/explorer/tile_visits.py", line 194, in _process_activity
geo-activity  |     if first_time is None or time < first_time:
geo-activity  |                              ^^^^^^^^^^^^^^^^^
geo-activity  |   File "timestamps.pyx", line 387, in pandas._libs.tslibs.timestamps._Timestamp.__richcmp__
geo-activity  | TypeError: Cannot compare tz-naive and tz-aware timestamps
```

The gpx track looks very normal:
```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1" creator="OsmAnd~ 5.0.5" xmlns="http://www.topografix.com/GPX/1/1" xmlns:osmand="https://osmand.net/docs/technical/osmand-file-formats/osmand-gpx" xmlns:gpxtpx="https://www8.garmin.com/xmlschemas/TrackPointExtensionv1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 https://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>2025-05-05_20-26_Mon</name>
  </metadata>
  <trk>
    <trkseg>
      <trkpt lat="51.yyyyyyy" lon="6.yyyyyyy">
        <ele>45.4</ele>
        <time>2025-05-05T18:26:49Z</time>
        <hdop>9.4</hdop>
      </trkpt>
      <trkpt lat="51.yyyyyyy" lon="6.yyyyyyy">
        <ele>38.7</ele>
        <time>2025-05-05T18:26:52Z</time>
        <hdop>4</hdop>
      </trkpt>
      <trkpt lat="51.yyyyyyy" lon="6.yyyyyyy">
        <ele>37.2</ele>
        <time>2025-05-05T18:27:02Z</time>
        <hdop>3.8</hdop>
        <extensions>
          <osmand:speed>2.1</osmand:speed>
        </extensions>
      </trkpt>
      <trkpt lat="51.yyyyyyy" lon="6.yyyyyyy">
        <ele>32.1</ele>
        <time>2025-05-05T18:27:05Z</time>
        <hdop>3.8</hdop>
        <extensions>
          <osmand:speed>3.5</osmand:speed>
        </extensions>
      </trkpt>
    ...
```

I suspect it has something to do with the new time zone fixer.
To start fresh i deleted the data directory and copied the activities back.
But i encountered another problem.

**Comment by martin-ueding** [comment]
Could you try out the time zone fixer at http://127.0.0.1:5000/time-zone-fixer/?

**Comment by martin-ueding** [comment]
Oh wait, that's in the tile visits. That can't work. I'll need to do something else there.

**Comment by martin-ueding** [comment]
Version 1.4.0 is now released and should fix that issue. Please let me know whether that works.

**Comment by beautiful-orca** [comment]
Upgrading from v1.2.0 to 1.4.1 and i have not encountered that error

**Comment by martin-ueding** [comment]
@smu and @momentmal ran into this as well.

I have the impression that this comes from a mix of time series where some are naive and some a time zone aware. That would happen if you imported some activities with an older version, some with a newer version and have not yet used the time zone fixer tool.

I have added a little fix that will assume that native times are UTC.

I'll release that fix shortly. Please delete `Cache/tile-state-2.pickle` and `Cache/work-tracker-tile-state.pickle` before starting it again.

**Comment by cni-md** [comment]
I just updated to 1.6.0 and run into the same problem.

`2025-07-13 12:55:52 geo_activity_playground.importers.directory INFO Importing Activities/Ride/touring/gadgetbridge-track-2025-07-07T15_58_52+02_00.gpx …
2025-07-13 12:55:53 geo_activity_playground.explorer.tile_visits INFO Tile visits are stored without time zone.
2025-07-13 12:55:53 geo_activity_playground.explorer.tile_visits WARNING Need to recompute Explorer Tiles due to deleted activities.
Tile visits: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 1471/1473 [01:16<00:00, 19.21it/s]
Importing activity files:   0%|                                                                                                                                                                                                        | 0/15 [01:17<?, ?it/s]
2025-07-13 12:57:09 geo_activity_playground.webui.app ERROR Exception on /upload/execute-reload [GET]
Traceback (most recent call last):
  File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/webui/authenticator.py", line 41, in wrapped_route
    return route(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/webui/blueprints/upload_blueprint.py", line 102, in execute_reload
    scan_for_activities(
  File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/webui/blueprints/upload_blueprint.py", line 121, in scan_for_activities
    import_from_directory(repository, tile_visit_accessor, config)
  File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/importers/directory.py", line 62, in import_from_directory
    import_from_file(
  File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/importers/directory.py", line 111, in import_from_file
    compute_tile_visits_new(repository, tile_visit_accessor)
  File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/explorer/tile_visits.py", line 183, in compute_tile_visits_new
    _process_activity(repository, tile_visit_accessor.tile_state, activity_id)
  File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/explorer/tile_visits.py", line 254, in _process_activity
    if first_time is None or time < first_time:
                             ^^^^^^^^^^^^^^^^^
  File "pandas/_libs/tslibs/timestamps.pyx", line 387, in pandas._libs.tslibs.timestamps._Timestamp.__richcmp__
TypeError: Cannot compare tz-naive and tz-aware timestamps
`

**Comment by cni-md** [comment]
_Please delete Cache/tile-state-2.pickle and Cache/work-tracker-tile-state.pickle before starting it again._
Did not solve the problem.

**Comment by martin-ueding** [comment]
Okay, this proves to be harder than I thought. Thanks for all your reports. I'll have to ponder this a bit more.

**Comment by martin-ueding** [comment]
I have added more error handling to version 1.7.0. Can you please try again and share the extended error message, please?

**Comment by cni-md** [comment]
You are getting closer ;) After the update 1.6.0 to 1.8.0

```
 File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/explorer/tile_visits.py", line 257, in _process_activity
    if first_time.tz is None:
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tz'
```

After scan new activities
```
File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/explorer/tile_visits.py", line 175, in compute_tile_visits_new
    if not _consistency_check(repository, tile_visit_accessor):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cni/.local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/explorer/tile_visits.py", line 157, in _consistency_check
    if not pd.isna(meta["first_time"]) and meta["first_time"].tzinfo is None:
                   ~~~~^^^^^^^^^^^^^^
KeyError: 'first_time'

```

**Comment by momentmal** [comment]
> After the update 1.6.0 to 1.8.0


Same error here, after a fresh strava archive import

Screenshot 1
<img width="2020" height="415" alt="Image" src="https://github.com/user-attachments/assets/360069cc-f54d-43b3-9e0e-21037bb3430b" />

Screenshot 2
<img width="2020" height="499" alt="Image" src="https://github.com/user-attachments/assets/f087da18-b94b-4d79-8080-1b025b287a14" />

**Comment by cni-md** [comment]
I modified .local/pipx/venvs/geo-activity-playground/lib/python3.11/site-packages/geo_activity_playground/explorer/tile_visits.py
line 257ff
```
              if first_time:
                    if first_time.tz is None:
                        first_time = first_time.tz_localize("UTC")
                if last_time:
                    if last_time.tz is None:
                        last_time = last_time.tz_localize("UTC")
```

and deleted Cache and database.sqlite and started from scratch.

No tz error and the import seems ok in the first glance. The general track statistics looks ok, BUT I have some strage speed plots on some tracks. The speed has 3 positions after decimal point.

<img width="428" height="359" alt="Image" src="https://github.com/user-attachments/assets/c19f0c51-7bc2-41c0-afaf-02a22e2786f9" />

2 days before recorded with the same setup looks ok.

<img width="409" height="364" alt="Image" src="https://github.com/user-attachments/assets/5dd3c98c-a7ce-4365-bd64-6678ebd9c86c" />

I set the Track segmentation to 0, no change. Some speed plots are binned and I get no speed histogram.

**Comment by momentmal** [comment]
> I've added that to version 1.8.1 now. You shouldn't need to reset anything, it should just work with existing state now.

I just renamed my cache folder and reserved (I had not checked for your comment yet stating we don't need to reset anything), the issues seems to be gone.

Also, apperently I can access Level 14 Tiles without the server crashing 😎
